name = "ConcurrentCollectionsBenchmarks"
uuid = "172d371b-ba13-4e7e-a6ad-f169f5735fdf"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[deps]
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ConcurrentCollections = "5060bff5-0b44-40c5-b522-fcd3ca5cecdd"
