name: Run tests

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        julia-version: ['~1.7.0-beta4', 'nightly']
        nthreads: ['1', '2']
        include:
          - os: macos-latest
            julia-version: 'nightly'
            nthreads: '2'
          - os: windows-latest
            julia-version: 'nightly'
            nthreads: '2'
      fail-fast: false
    name: Test Julia ${{ matrix.julia-version }} ${{ matrix.os }} nthreads=${{ matrix.nthreads }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      # Use `JULIA_PKG_SERVER` mitigation implemented in julia-buildpkg:
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_NUM_THREADS: ${{ matrix.nthreads }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
